# Generated by Django 2.2.1 on 2019-05-27 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenProduccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(verbose_name='Descripcion')),
                ('numero_lote', models.CharField(max_length=50, verbose_name='Numero de lote')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad a fabricar')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de Entrega')),
                ('codigo_pedido', models.CharField(max_length=50, verbose_name='Codigo de pedido')),
                ('caducidad', models.DateField(verbose_name='Caducidad')),
            ],
            options={
                'verbose_name': 'Orden de Produccion',
                'verbose_name_plural': 'Ordenes de Produccion',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, verbose_name='Codigo')),
                ('descripcion', models.TextField(verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
    ]
